services:
  # Backend API service
  - type: web
    name: mamovie-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: CONSUMER_KEY
        sync: false
      - key: CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: CALLBACK_URL
        value: https://mamovie-api.onrender.com/callback

  # Frontend static site
  - type: web
    name: mamovie-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.svg
        name: Content-Type
        value: image/svg+xml
      - path: /*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /*.png
        name: Content-Type
        value: image/png
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://mamovie-api.onrender.com/api/v1